require_relative './config/environment'
require 'sinatra/activerecord/rake'

desc "Start our app console"
task :console do
  ActiveRecord::Base.logger = Logger.new(STDOUT)
  Pry.start
end

desc "puts a stupid message"
task :helloworld do
  puts "Yo what's up world it me ur rake"
end
